# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number
    # increment_version_number(
    #   bump_type: "patch"
    # )    
    # get_certificates           # invokes cert
    # get_provisioning_profile   # invokes sigh
    sync_code_signing(type: "appstore")
    gym(scheme: "Piano",
      clean: true,
      workspace: "Piano.xcworkspace",
      buildlog_path: 'fastlane/logs'
    )
    pilot(skip_waiting_for_build_processing: true)
  end

  lane :icon do
    appicon(
      appicon_devices: [:ipad, :iphone, :ios_marketing],
      appicon_path: "Piano/Assets.xcassets"
    )
  end

  lane :refresh_dsyms do
    download_dsyms(version: "latest")
    # download_dsyms                  # Download dSYM files from iTC
    # download_dsyms(version: "1.0.24", build_number: "137")
    upload_symbols_to_crashlytics   # Upload them to Crashlytics
    clean_build_artifacts           # Delete the local dSYM files
  end

  lane :release do 
    increment_build_number
    increment_version_number(
      bump_type: "patch" # Automatically increment patch version number
    )
    get_certificates           # invokes cert
    get_provisioning_profile   # invokes sigh
    sync_code_signing(type: "appstore")
    gym(
      scheme: "Piano",
      clean: true,
      workspace: "Piano.xcworkspace",
      buildlog_path: 'fastlane/logs',
      include_bitcode: true
    )
    deliver(
      skip_metadata: true,
      skip_screenshots: true,
      force: true,
      automatic_release: true
    )
  end
end
